---
title: "Assignmeant_8404"
author: "SATISH"
date: "11/4/2021"
output: html_document
---
1  Cluster Analysis
#Reading the dataset
```{r}
filename="C:/Users/pilla/Desktop/8404_Assignment/Ch10Ex11.csv"
gexpr=read.csv(filename,header = FALSE)
df=gexpr
dim(df)
```
#Transpose the matrix 
```{r}
g=t(gexpr)
dim(g)
```
#(a)Hierarchical clustering(correlation-based distance)
```{r}
dim(df)
r_obs=cor(df)
d_cor=1-r_obs
d1=as.dist(d_cor)
```

```{r}
hc_c=hclust(d1,method = "single")
#class(hc_c)
#str(hc_c)
```
```{r}
plot(hc_c,cex=0.5,mian="")
```

#complete-linkage
```{r}
hc_c2=hclust(d1,method = "complete")
plot(hc_c2,cex=0.5,mian="")
```
#average-linkage.
```{r}
hc_c3=hclust(d1,method = "average")
plot(hc_c3,cex=0.5,mian="")
```
#ecludian distance
```{r}
d2=dist(g)
hc_c2=hclust(d2,method = "single")
plot(hc_c2,cex=0.5,mian="")
```
2)K-means algorithm

```{r}
k=10
SS_W=numeric(k)
km_fit=list()
for(i in 1:k){
  km_fit[[i]]=kmeans(g,i,iter.max = 50,nstart = 20)
  SS_W[i]=km_fit[[i]]$tot.withinss
}
  
```

```{r}
plot(1:k, SS_W,type="l",xlab="K",ylab="SS_W")
```

```{r}
plot(km_fit[[4]]$cluster)
df=data.frame(km_fit[[4]]$cluster)
df
```
#LOGISTIC REGRESSION
```{r}

```

